name: Aleksandr Aibulatov
markdown: redcarpet
pygments: true
github: https://www.github.com/zapix
about: I am an django/python developer at http://milosolutions.com
urls:
    - text: github
      url: https://github.com/zapix
    - text: twitter
      url: https://twitter.com/Zapix
    - text: email
      url: mailto:exaem@exaem.co.uk
